name: R Package Test on Rocky Linux 9

on:
  push:
    branches:
      - mesh
  pull_request:
    branches:
      - mesh

jobs:
  test:
    runs-on: ubuntu-latest  # Using an Ubuntu runner to host the Docker container
    container:
      image: rockylinux/rockylinux:9  # Specify the Docker image for Rocky Linux 9

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install R and dependencies
        run: |
          dnf install -y dnf-plugins-core
          dnf config-manager --set-enabled devel
          dnf install -y epel-release
          dnf install -y R
          # Installing system dependencies for R packages
          dnf install -y gdal-devel proj-devel geos-devel udunits2-devel
          # Install R packages dependencies
          R -e 'install.packages(c("testthat","TMB", "fmesher", "fields", "marmap", "sf", "splancs", "ellipse", "RcppEigen"), repos = "http://cran.rstudio.com/")'

      - name: Install the R package and run tests
        run: |
          cd spatioTemporalIndices  # Change directory to the package root
          pwd  # Print working directory to verify correct path
          R CMD INSTALL .
          R -e 'testthat::test_dir("tests/")'