name: R Package Test on Rocky Linux 9

on:
  push:
    branches:
      - mesh
  pull_request:
    branches:
      - mesh

jobs:
  test:
    runs-on: ubuntu-latest  # Using an Ubuntu runner to host the Docker container
    container:
      image: rockylinux/rockylinux:9  # Specify the Docker image for Rocky Linux 9

    steps:
      - name: Install dependencies
        run: |
          dnf install -y epel-release dnf-plugins-core
          dnf config-manager --set-enabled devel
          dnf install -y R wget git gcc-c++ make \
            gdal-devel proj-devel geos-devel udunits2-devel \
            libcurl-devel openssl-devel libxml2-devel \
            cairo-devel libpng-devel freetype-devel \
            fontconfig-devel mesa-libGL-devel harfbuzz-devel fribidi-devel \
            xorg-x11-server-Xvfb xorg-x11-fonts-Type1 dejavu-sans-fonts

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install R package dependencies
        run: |
          R -e 'install.packages(c("testthat", "TMB", "fmesher", "fields", "marmap", "sf", "splancs", "ellipse", "RcppEigen"), dependencies = TRUE, repos = "http://cran.rstudio.com/")'

      - name: Install the R package and run tests
        run: |
          cd spatioTemporalIndices  # Change directory to the package root
          pwd  # Print working directory to verify correct path
          R CMD INSTALL .
          R -e 'testthat::test_dir("tests/")'